csesoc/csesoc.unsw.edu.au

src/main.go, templates/landingPage.html
- Adds a HTML server using the Echo framework
Serves HTML files
None
- Closes #16
=> Serve HTML using Echo

src/views/Home.vue
- Fix left over code to allow HomeGreeting component to load correctly
Fixes component
None
None
=> Fix missing home greeting component

src/components/Slider.vue
horizontal scrolling display for landing page
=> add slider component

src/components/LoginForm.vue
- Form UX tweaks
Improve UX
None
=> tweak form

CODEOWNERS
Hey @glebme need your approval to gain access to repository!
=> Gain repository access

CODEOWNERS, server/faq_test.go
- Added faq_test.go
To conform to new testing practices
=> CW-40 Added faq_test.go

backend/server/sponsor.go, backend/server/sponsor_test.go, backend/server/static/sponsor.json, frontend/src/components/Footer.vue
- added sponsor.json
- change the sponsorSetup onto our local file system instead of a get request
- to get the latest update of the sponsor list
=> CW-61 Feat/scrape sponsors

frontend/src/utils/APIClient.js, frontend/src/utils/Constants.js
-Fix routing constants.
Weren't calling the correct api url
=> Fix routing constants.

README.md
- Fix README to reflect changes to the API documentation
Needed to clearly layout how to access our API documentation and why we chose Swagger.
=> Fix README to reflect changes on how the API is documented

backend/go.mod, backend/go.sum, backend/server/sponsor/sponsor.go, backend/server/sponsor/sponsor_test.go
I have fixed the inserts to make sure that if it already exists it won't try to insert into database again. Also added in the sponsor url for the link. I also couldn't find the tiktok link. Let me know what you guys think of the images as well!
=> CW-115 Update site components for social media

README.md
- Added a *Setting up environment variables* section to the README file.
- Added a *Security* section to the README file further explaining these security aspects.
I forgot to include it in the pull request that introduced this feature. So I'm sending it through as a `fix` branch.
=> Update .env file documentation

backend/server/sponsor/sponsor.go, frontend/src/utils/APIClient.js, frontend/src/views/Engage.vue
- Remove URL validation from the Logo field in the Sponsor struct.
- Use `getClient()` to construct the options of socials and faqs API requests.
- Fix naming convention in the socials and faqs component of the `APIClient`.
To fix a small bug and improve the quality of the code.
Shoutout to @glebme for pointing this out!!
=> Fix cohesiveness issues in APIClient

backend/server/sponsor/sponsor.go, frontend/src/components/EnquiryForm.vue, frontend/src/components/Footer.vue, frontend/src/components/Sidebar.vue, frontend/src/components/SponsorModal.vue, frontend/src/plugins/router.js, frontend/src/utils/APIClient.js, frontend/src/views/Sponsor.vue
This PR deals with the Sponsors Page, it follows closely on how the design of the wireframe works. Error handling is not implemented in this iteration.
=> CW-43 Displaying Sponsors

frontend/src/components/EventGrid.vue
- Update event card design to match wireframe
- Match design decisions made by team
=> CW-153 Events on homepage

README.md
_Update Documentation to reflect use of new frontend testing framework_
Straightforward update to reflect new adoption of Cypress framework
Reminded by @sergiomercado19. Thank you.
=> CW-165 Update README.md

frontend/src/styles/abstracts/_mixins.scss, frontend/src/styles/abstracts/mixins/_linear-gradient.scss
_Add linear gradient for next years team_
We have linear gradients as part of our design style-guide and hence would be handy for those implementing next year to already have a mixin to do gradients.
=> CW-173 Colour SCSS

frontend/cypress/integration/components/infiniteSlideshow.spec.js, frontend/src/components/InfiniteSlideshow.vue
- Created a testing file for the infinite slideshow.
- Added the necessary data-cy attributes to enable their interaction with Cypress.
Part of our current milestone to retroactively create tests for all Vue components.
Since Cypress is not tuned for visual testing, I'm ensuring that the banners are present and that the CSS animation properties are set.
=> CW-178 Infinite slideshow testing

frontend/src/components/Footer.vue
This pull requests, refactors the footer to have the design mentioned in adobe XD
=> CW-155 Footer redesign

backend/static/social.json, frontend/src/components/CommunityLink.vue, frontend/src/components/Footer.vue, frontend/src/components/Menu.vue, frontend/src/views/About.vue, frontend/src/views/Engage.vue, frontend/src/views/Home.vue
- Make minor wording fixes for consistency/readability
- Some sentences/phrases could be worded better.
- Some mismatches existed with formatting of menu/footer text.
- Updated Discord links, as the verification method has now changed.
=> CW-226 Wording fixes

frontend/cypress/integration/components/resources.spec.js, frontend/src/views/Home.vue
Add Cypress tests for the resources section of the landing page.
Part of our plan to retrospectively write frontend tests.
Frontend testing is an essential part of our CI workflow, and no tests existed for resources yet.
I couldn't figure out how to test hover, but I am checking that the CSS transition property is set.
=> CW-223 Resources testing

frontend/cypress/integration/components/menu.spec.js, frontend/src/App.vue, frontend/src/components/Menu.vue
Add Cypress tests for the Menu component of the website.
Part of our plan to retrospectively write frontend tests.
Frontend testing is an essential part of our CI workflow, and no tests existed for the menu yet.
These tests check both, the functionality of internal page links, and the presence of external social links.
=> CW-205 Menu testing

backend/server/faq/faq_test.go
_Reintroduce the faq test to try and recreate github action bug._
_Add a brief and concise imperative sentence on what this PR does._
_Example: Edit PR template to improve efficiency_
All apart of the testing.
If it continues to fail then it has something to do with our sever. Else it was github all along.
#97
=> Re-introducing FAQ Tests

backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/main.go, backend/server/faq/faq.go, backend/server/resources/resources.go, backend/server/social/social.go, backend/static/social.json
- Load _faqs_ and _socials_ on the database upon server startup.
- Remove unused `id` field from Social links.
This change is an effort to restructure the database to become more generic, in preparation for the CMS.
_Reviewer note_: when testing these changes use SwaggerUI to make sure all the requests are returning the static JSON file from the backend. Additionally, check that the _socials links_ and _faqs_ have loaded in the Engage page.
=> CW-96 Restructure Database to become more generic

backend/server/constants.go, backend/server/mailing/mailing.go
Moved all `mailing.go` constants to the utility module's `constants.go` file.
All constants should be in the `constants.go` file.
I tested the MAILJET_TOKEN was still working.
=> CW-244 Move mailing constants

backend/main.go
=> Add fonts to static dist files to be searched by server.

frontend/src/views/Home/Home.vue, frontend/src/views/Home/Mission.vue, frontend/src/views/Home/Showcase.vue, frontend/src/views/Home/Slideshow.vue, frontend/src/views/Home/StudentResources.vue
_Refactor the data that was on the landing page into data props._
The change needed to occur to allow an easy way to visualise what data needed to be served from the back-end and look for ways to best present this information. By refactoring the information into the vue data props, we set up a simple and fast way to transfer to using APIs because we can just pass the props down from the API calls made on the Home page.
=> CW-231 Refactor Data

frontend/cypress/integration/components/mission.spec.js, frontend/cypress/integration/components/showcase.spec.js, frontend/src/views/Home/Mission.vue
_Added testing to the mission statement._
As it pertains to changes in functionality due to the CMS, while adding responsive design I have noticed that we have not created testing for mission. I have done so.
=> CW-255 Mission Testing

backend/server/events/events.go, backend/server/faq/faq.go, backend/server/mailing/mailing.go, backend/server/resources/resources.go, backend/server/social/social.go, backend/server/sponsor/sponsor.go
_Change failure tag to conform to API guidelines._
I had accidentally deleted my images for the project and when I tried to rebuild, swag init errored from a ParseComment error for 500 "Internal Server Error". By removing subsequent header tags and conforming to the correct format for the API call the issue was resolved. This was then replicated for all other Failure tags for consistency.
N/A
=> CW-258 Change failure tag to conform to API guidelines.

frontend/package-lock.json
_Please remove everything in italics._
_Add a brief and concise imperative sentence on what this PR does._
_Example: Edit PR template to improve efficiency_
_Provide a brief description based on the type of change._
1. _Functionality - explain the problem, why the solution was chosen, and any specifics that might be worth highlighting_
2. _Refactoring  - why there was a need for the change, how the changes address this problem, and steps to take to avoid the same mistakes (better documentation, another step in PR reviews, simplification of system design)_
_Add any other comments about the PR here. In particular add information relating where a reviewer should start and any specific concerns that you came across._
=> Dependencies upgraded

frontend/cypress/integration/components/mailingForm.spec.js, frontend/src/plugins/router.js
Fixed by removing .vue in /router.js
=> Fixed vue extension error

frontend/src/components/Footer.vue, frontend/src/components/Menu.vue, frontend/src/views/Home/Showcase.vue
Reworded splash screen to be more friendly. Part of reworking old website for deployment 2021
Old splash received negatively by most people
=> Changed splash to hello world

frontend/src/views/Home/Showcase.vue
made the join us button redirect to sparc
=> made button click

frontend/src/views/Sponsor.vue
down button finally works, flips from down to up
also brings user to the very top
when clicked sends user to the next title.
=> button finally working

frontend/src/components/Footer.vue
_Please remove everything in italics._
_Add a brief and concise imperative sentence on what this PR does._
_Example: Edit PR template to improve efficiency_
_Provide a brief description based on the type of change._
1. _Functionality - explain the problem, why the solution was chosen, and any specifics that might be worth highlighting_
2. _Refactoring  - why there was a need for the change, how the changes address this problem, and steps to take to avoid the same mistakes (better documentation, another step in PR reviews, simplification of system design)_
_Add any other comments about the PR here. In particular add information relating where a reviewer should start and any specific concerns that you came across._
=> sped up footer hover animation
